run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - ineffassign
    - typecheck
    - unused

  disable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - dupl
